require("dashboard").setup({
  theme = 'hyper',
  config = {
    packages = {
      enable = true,
    },
    projects = {
      enable = true,
      limit = 8,
      icon = ' ',
      label = 'Projects',
      action = 'Telescope projects cwd='
    },
    mru = {
      enable = true,
      limit = 8,
      icon = ' ',
      label = 'Recent files',
      action = 'Telescope oldfiles',
      cwd_only = false,
    },
    footer = { "" },
    -- week_header = {
    --   enable = true,
    -- },
    header = {
      "",
      " ███╗   ██╗ ███████╗ ██████╗  ██╗   ██╗ ██╗ ███╗   ███╗",
      " ████╗  ██║ ██╔════╝██╔═══██╗ ██║   ██║ ██║ ████╗ ████║",
      " ██╔██╗ ██║ █████╗  ██║   ██║ ██║   ██║ ██║ ██╔████╔██║",
      " ██║╚██╗██║ ██╔══╝  ██║   ██║ ╚██╗ ██╔╝ ██║ ██║╚██╔╝██║",
      " ██║ ╚████║ ███████╗╚██████╔╝  ╚████╔╝  ██║ ██║ ╚═╝ ██║",
      " ╚═╝  ╚═══╝ ╚══════╝ ╚═════╝    ╚═══╝   ╚═╝ ╚═╝     ╚═╝",
      "",
    },
    shortcut = {
      {
        icon = " ",
        icon_hl = "DashboardShortCutIcon",
        desc = "Jump to book marks",
        group = "@property",
        action = function() require("telescope.builtin").marks() end,
        key = "b",
      },
      {
        icon = " ",
        icon_hl = "DashboardShortCutIcon",
        desc = "Change Colorscheme",
        group = "Label",
        action = function() require("telescope.builtin").colorscheme() end,
        key = "t",
      },
      {
        icon = " ",
        icon_hl = "DashboardShortCutIcon",
        desc = "Recently opened files",
        group = "DiagnosticHint",
        action = function() require("telescope.builtin").oldfiles() end,
        key = "h",
      },
      {
        icon = " ",
        icon_hl = "DashboardShortCutIcon",
        desc = "Recently last session",
        group = "DiagnosticWarn",
        action = function() vim.cmd("SessionLoad") end,
        key = "s",
      },
      {
        icon = " ",
        icon_hl = "DashboardShortCutIcon",
        desc = "Find  word",
        group = "Number",
        action = function() require("telescope.builtin").live_grep() end,
        key = "a",
      },
      {
        icon = " ",
        icon_hl = "DashboardShortCutIcon",
        desc = "Find  File",
        group = "DiagnosticError",
        action = function() require("telescope.builtin").find_files() end,
        key = "f",
      },
    },
  },
})
